server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE # forwarded uri (유레카 서버에 등록된 앱 이름)
          predicates:
            - Path=/user-service/** # 사용자가 요청한 주소
          filters:
            - name: LogFilter
              args:
                baseMessage: Welcome to Jiwon's Jimart. This is test base message.
                preLogger: true
                postLogger: true

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
